/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package towerdefense;

/**
 *
 * @author jxw5676
 */
public class gridUI extends javax.swing.JFrame {

    /**
     * Creates new form GameUIv2
     */
    public gridUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameGrid = new javax.swing.JPanel();
        p1x1 = new javax.swing.JPanel();
        p1x2 = new javax.swing.JPanel();
        p1x3 = new javax.swing.JPanel();
        p1x4 = new javax.swing.JPanel();
        p1x5 = new javax.swing.JPanel();
        p1x6 = new javax.swing.JPanel();
        p1x7 = new javax.swing.JPanel();
        p1x8 = new javax.swing.JPanel();
        p2x1 = new javax.swing.JPanel();
        p2x2 = new javax.swing.JPanel();
        p2x3 = new javax.swing.JPanel();
        p2x4 = new javax.swing.JPanel();
        p2x5 = new javax.swing.JPanel();
        p2x6 = new javax.swing.JPanel();
        p2x7 = new javax.swing.JPanel();
        p2x8 = new javax.swing.JPanel();
        p3x1 = new javax.swing.JPanel();
        p3x2 = new javax.swing.JPanel();
        p3x3 = new javax.swing.JPanel();
        p3x4 = new javax.swing.JPanel();
        p3x5 = new javax.swing.JPanel();
        p3x6 = new javax.swing.JPanel();
        p3x7 = new javax.swing.JPanel();
        p3x8 = new javax.swing.JPanel();
        p4x1 = new javax.swing.JPanel();
        p4x2 = new javax.swing.JPanel();
        p4x3 = new javax.swing.JPanel();
        p4x4 = new javax.swing.JPanel();
        p4x5 = new javax.swing.JPanel();
        p4x6 = new javax.swing.JPanel();
        p4x7 = new javax.swing.JPanel();
        p4x8 = new javax.swing.JPanel();
        p5x1 = new javax.swing.JPanel();
        p5x2 = new javax.swing.JPanel();
        p5x3 = new javax.swing.JPanel();
        p5x4 = new javax.swing.JPanel();
        p5x5 = new javax.swing.JPanel();
        p5x6 = new javax.swing.JPanel();
        p5x7 = new javax.swing.JPanel();
        p5x8 = new javax.swing.JPanel();
        p6x1 = new javax.swing.JPanel();
        p6x2 = new javax.swing.JPanel();
        p6x3 = new javax.swing.JPanel();
        p6x4 = new javax.swing.JPanel();
        p6x5 = new javax.swing.JPanel();
        p6x6 = new javax.swing.JPanel();
        p6x7 = new javax.swing.JPanel();
        p6x8 = new javax.swing.JPanel();
        p7x1 = new javax.swing.JPanel();
        p7x2 = new javax.swing.JPanel();
        p7x3 = new javax.swing.JPanel();
        p7x4 = new javax.swing.JPanel();
        p7x5 = new javax.swing.JPanel();
        p7x6 = new javax.swing.JPanel();
        p7x7 = new javax.swing.JPanel();
        p7x8 = new javax.swing.JPanel();
        p8x1 = new javax.swing.JPanel();
        p8x2 = new javax.swing.JPanel();
        p8x3 = new javax.swing.JPanel();
        p8x4 = new javax.swing.JPanel();
        p8x5 = new javax.swing.JPanel();
        p8x6 = new javax.swing.JPanel();
        p8x7 = new javax.swing.JPanel();
        p8x8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gameGrid.setBackground(new java.awt.Color(204, 204, 255));
        gameGrid.setLayout(new java.awt.GridLayout(8, 8));

        p1x1.setBackground(new java.awt.Color(153, 153, 255));
        p1x1.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p1x1Layout = new javax.swing.GroupLayout(p1x1);
        p1x1.setLayout(p1x1Layout);
        p1x1Layout.setHorizontalGroup(
            p1x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p1x1Layout.setVerticalGroup(
            p1x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p1x1);

        p1x2.setBackground(new java.awt.Color(255, 255, 102));
        p1x2.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p1x2Layout = new javax.swing.GroupLayout(p1x2);
        p1x2.setLayout(p1x2Layout);
        p1x2Layout.setHorizontalGroup(
            p1x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p1x2Layout.setVerticalGroup(
            p1x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p1x2);

        p1x3.setBackground(new java.awt.Color(153, 153, 255));
        p1x3.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p1x3Layout = new javax.swing.GroupLayout(p1x3);
        p1x3.setLayout(p1x3Layout);
        p1x3Layout.setHorizontalGroup(
            p1x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p1x3Layout.setVerticalGroup(
            p1x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p1x3);

        p1x4.setBackground(new java.awt.Color(153, 153, 255));
        p1x4.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p1x4Layout = new javax.swing.GroupLayout(p1x4);
        p1x4.setLayout(p1x4Layout);
        p1x4Layout.setHorizontalGroup(
            p1x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p1x4Layout.setVerticalGroup(
            p1x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p1x4);

        p1x5.setBackground(new java.awt.Color(153, 153, 255));
        p1x5.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p1x5Layout = new javax.swing.GroupLayout(p1x5);
        p1x5.setLayout(p1x5Layout);
        p1x5Layout.setHorizontalGroup(
            p1x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p1x5Layout.setVerticalGroup(
            p1x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p1x5);

        p1x6.setBackground(new java.awt.Color(153, 153, 255));
        p1x6.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p1x6Layout = new javax.swing.GroupLayout(p1x6);
        p1x6.setLayout(p1x6Layout);
        p1x6Layout.setHorizontalGroup(
            p1x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p1x6Layout.setVerticalGroup(
            p1x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p1x6);

        p1x7.setBackground(new java.awt.Color(153, 153, 255));
        p1x7.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p1x7Layout = new javax.swing.GroupLayout(p1x7);
        p1x7.setLayout(p1x7Layout);
        p1x7Layout.setHorizontalGroup(
            p1x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p1x7Layout.setVerticalGroup(
            p1x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p1x7);

        p1x8.setBackground(new java.awt.Color(153, 153, 255));
        p1x8.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p1x8Layout = new javax.swing.GroupLayout(p1x8);
        p1x8.setLayout(p1x8Layout);
        p1x8Layout.setHorizontalGroup(
            p1x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p1x8Layout.setVerticalGroup(
            p1x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p1x8);

        p2x1.setBackground(new java.awt.Color(153, 153, 255));
        p2x1.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p2x1Layout = new javax.swing.GroupLayout(p2x1);
        p2x1.setLayout(p2x1Layout);
        p2x1Layout.setHorizontalGroup(
            p2x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p2x1Layout.setVerticalGroup(
            p2x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p2x1);

        p2x2.setBackground(new java.awt.Color(255, 255, 102));
        p2x2.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p2x2Layout = new javax.swing.GroupLayout(p2x2);
        p2x2.setLayout(p2x2Layout);
        p2x2Layout.setHorizontalGroup(
            p2x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p2x2Layout.setVerticalGroup(
            p2x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p2x2);

        p2x3.setBackground(new java.awt.Color(153, 153, 255));
        p2x3.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p2x3Layout = new javax.swing.GroupLayout(p2x3);
        p2x3.setLayout(p2x3Layout);
        p2x3Layout.setHorizontalGroup(
            p2x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p2x3Layout.setVerticalGroup(
            p2x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p2x3);

        p2x4.setBackground(new java.awt.Color(153, 153, 255));
        p2x4.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p2x4Layout = new javax.swing.GroupLayout(p2x4);
        p2x4.setLayout(p2x4Layout);
        p2x4Layout.setHorizontalGroup(
            p2x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p2x4Layout.setVerticalGroup(
            p2x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p2x4);

        p2x5.setBackground(new java.awt.Color(255, 255, 102));
        p2x5.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p2x5Layout = new javax.swing.GroupLayout(p2x5);
        p2x5.setLayout(p2x5Layout);
        p2x5Layout.setHorizontalGroup(
            p2x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p2x5Layout.setVerticalGroup(
            p2x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p2x5);

        p2x6.setBackground(new java.awt.Color(255, 255, 102));
        p2x6.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p2x6Layout = new javax.swing.GroupLayout(p2x6);
        p2x6.setLayout(p2x6Layout);
        p2x6Layout.setHorizontalGroup(
            p2x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p2x6Layout.setVerticalGroup(
            p2x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p2x6);

        p2x7.setBackground(new java.awt.Color(255, 255, 102));
        p2x7.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p2x7Layout = new javax.swing.GroupLayout(p2x7);
        p2x7.setLayout(p2x7Layout);
        p2x7Layout.setHorizontalGroup(
            p2x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p2x7Layout.setVerticalGroup(
            p2x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p2x7);

        p2x8.setBackground(new java.awt.Color(153, 153, 255));
        p2x8.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p2x8Layout = new javax.swing.GroupLayout(p2x8);
        p2x8.setLayout(p2x8Layout);
        p2x8Layout.setHorizontalGroup(
            p2x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p2x8Layout.setVerticalGroup(
            p2x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p2x8);

        p3x1.setBackground(new java.awt.Color(153, 153, 255));
        p3x1.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p3x1Layout = new javax.swing.GroupLayout(p3x1);
        p3x1.setLayout(p3x1Layout);
        p3x1Layout.setHorizontalGroup(
            p3x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p3x1Layout.setVerticalGroup(
            p3x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p3x1);

        p3x2.setBackground(new java.awt.Color(255, 255, 102));
        p3x2.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p3x2Layout = new javax.swing.GroupLayout(p3x2);
        p3x2.setLayout(p3x2Layout);
        p3x2Layout.setHorizontalGroup(
            p3x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p3x2Layout.setVerticalGroup(
            p3x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p3x2);

        p3x3.setBackground(new java.awt.Color(153, 153, 255));
        p3x3.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p3x3Layout = new javax.swing.GroupLayout(p3x3);
        p3x3.setLayout(p3x3Layout);
        p3x3Layout.setHorizontalGroup(
            p3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p3x3Layout.setVerticalGroup(
            p3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p3x3);

        p3x4.setBackground(new java.awt.Color(153, 153, 255));
        p3x4.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p3x4Layout = new javax.swing.GroupLayout(p3x4);
        p3x4.setLayout(p3x4Layout);
        p3x4Layout.setHorizontalGroup(
            p3x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p3x4Layout.setVerticalGroup(
            p3x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p3x4);

        p3x5.setBackground(new java.awt.Color(255, 255, 102));
        p3x5.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p3x5Layout = new javax.swing.GroupLayout(p3x5);
        p3x5.setLayout(p3x5Layout);
        p3x5Layout.setHorizontalGroup(
            p3x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p3x5Layout.setVerticalGroup(
            p3x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p3x5);

        p3x6.setBackground(new java.awt.Color(153, 153, 255));
        p3x6.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p3x6Layout = new javax.swing.GroupLayout(p3x6);
        p3x6.setLayout(p3x6Layout);
        p3x6Layout.setHorizontalGroup(
            p3x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p3x6Layout.setVerticalGroup(
            p3x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p3x6);

        p3x7.setBackground(new java.awt.Color(255, 255, 102));
        p3x7.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p3x7Layout = new javax.swing.GroupLayout(p3x7);
        p3x7.setLayout(p3x7Layout);
        p3x7Layout.setHorizontalGroup(
            p3x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p3x7Layout.setVerticalGroup(
            p3x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p3x7);

        p3x8.setBackground(new java.awt.Color(153, 153, 255));
        p3x8.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p3x8Layout = new javax.swing.GroupLayout(p3x8);
        p3x8.setLayout(p3x8Layout);
        p3x8Layout.setHorizontalGroup(
            p3x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p3x8Layout.setVerticalGroup(
            p3x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p3x8);

        p4x1.setBackground(new java.awt.Color(153, 153, 255));
        p4x1.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p4x1Layout = new javax.swing.GroupLayout(p4x1);
        p4x1.setLayout(p4x1Layout);
        p4x1Layout.setHorizontalGroup(
            p4x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p4x1Layout.setVerticalGroup(
            p4x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p4x1);

        p4x2.setBackground(new java.awt.Color(255, 255, 102));
        p4x2.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p4x2Layout = new javax.swing.GroupLayout(p4x2);
        p4x2.setLayout(p4x2Layout);
        p4x2Layout.setHorizontalGroup(
            p4x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p4x2Layout.setVerticalGroup(
            p4x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p4x2);

        p4x3.setBackground(new java.awt.Color(153, 153, 255));
        p4x3.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p4x3Layout = new javax.swing.GroupLayout(p4x3);
        p4x3.setLayout(p4x3Layout);
        p4x3Layout.setHorizontalGroup(
            p4x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p4x3Layout.setVerticalGroup(
            p4x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p4x3);

        p4x4.setBackground(new java.awt.Color(153, 153, 255));
        p4x4.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p4x4Layout = new javax.swing.GroupLayout(p4x4);
        p4x4.setLayout(p4x4Layout);
        p4x4Layout.setHorizontalGroup(
            p4x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p4x4Layout.setVerticalGroup(
            p4x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p4x4);

        p4x5.setBackground(new java.awt.Color(255, 255, 102));
        p4x5.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p4x5Layout = new javax.swing.GroupLayout(p4x5);
        p4x5.setLayout(p4x5Layout);
        p4x5Layout.setHorizontalGroup(
            p4x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p4x5Layout.setVerticalGroup(
            p4x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p4x5);

        p4x6.setBackground(new java.awt.Color(153, 153, 255));
        p4x6.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p4x6Layout = new javax.swing.GroupLayout(p4x6);
        p4x6.setLayout(p4x6Layout);
        p4x6Layout.setHorizontalGroup(
            p4x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p4x6Layout.setVerticalGroup(
            p4x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p4x6);

        p4x7.setBackground(new java.awt.Color(255, 255, 102));
        p4x7.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p4x7Layout = new javax.swing.GroupLayout(p4x7);
        p4x7.setLayout(p4x7Layout);
        p4x7Layout.setHorizontalGroup(
            p4x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p4x7Layout.setVerticalGroup(
            p4x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p4x7);

        p4x8.setBackground(new java.awt.Color(153, 153, 255));
        p4x8.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p4x8Layout = new javax.swing.GroupLayout(p4x8);
        p4x8.setLayout(p4x8Layout);
        p4x8Layout.setHorizontalGroup(
            p4x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p4x8Layout.setVerticalGroup(
            p4x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p4x8);

        p5x1.setBackground(new java.awt.Color(153, 153, 255));
        p5x1.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p5x1Layout = new javax.swing.GroupLayout(p5x1);
        p5x1.setLayout(p5x1Layout);
        p5x1Layout.setHorizontalGroup(
            p5x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p5x1Layout.setVerticalGroup(
            p5x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p5x1);

        p5x2.setBackground(new java.awt.Color(255, 255, 102));
        p5x2.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p5x2Layout = new javax.swing.GroupLayout(p5x2);
        p5x2.setLayout(p5x2Layout);
        p5x2Layout.setHorizontalGroup(
            p5x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p5x2Layout.setVerticalGroup(
            p5x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p5x2);

        p5x3.setBackground(new java.awt.Color(153, 153, 255));
        p5x3.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p5x3Layout = new javax.swing.GroupLayout(p5x3);
        p5x3.setLayout(p5x3Layout);
        p5x3Layout.setHorizontalGroup(
            p5x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p5x3Layout.setVerticalGroup(
            p5x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p5x3);

        p5x4.setBackground(new java.awt.Color(153, 153, 255));
        p5x4.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p5x4Layout = new javax.swing.GroupLayout(p5x4);
        p5x4.setLayout(p5x4Layout);
        p5x4Layout.setHorizontalGroup(
            p5x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p5x4Layout.setVerticalGroup(
            p5x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p5x4);

        p5x5.setBackground(new java.awt.Color(255, 255, 102));
        p5x5.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p5x5Layout = new javax.swing.GroupLayout(p5x5);
        p5x5.setLayout(p5x5Layout);
        p5x5Layout.setHorizontalGroup(
            p5x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p5x5Layout.setVerticalGroup(
            p5x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p5x5);

        p5x6.setBackground(new java.awt.Color(153, 153, 255));
        p5x6.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p5x6Layout = new javax.swing.GroupLayout(p5x6);
        p5x6.setLayout(p5x6Layout);
        p5x6Layout.setHorizontalGroup(
            p5x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p5x6Layout.setVerticalGroup(
            p5x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p5x6);

        p5x7.setBackground(new java.awt.Color(255, 255, 102));
        p5x7.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p5x7Layout = new javax.swing.GroupLayout(p5x7);
        p5x7.setLayout(p5x7Layout);
        p5x7Layout.setHorizontalGroup(
            p5x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p5x7Layout.setVerticalGroup(
            p5x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p5x7);

        p5x8.setBackground(new java.awt.Color(153, 153, 255));
        p5x8.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p5x8Layout = new javax.swing.GroupLayout(p5x8);
        p5x8.setLayout(p5x8Layout);
        p5x8Layout.setHorizontalGroup(
            p5x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p5x8Layout.setVerticalGroup(
            p5x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p5x8);

        p6x1.setBackground(new java.awt.Color(153, 153, 255));
        p6x1.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p6x1Layout = new javax.swing.GroupLayout(p6x1);
        p6x1.setLayout(p6x1Layout);
        p6x1Layout.setHorizontalGroup(
            p6x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p6x1Layout.setVerticalGroup(
            p6x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p6x1);

        p6x2.setBackground(new java.awt.Color(255, 255, 102));
        p6x2.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p6x2Layout = new javax.swing.GroupLayout(p6x2);
        p6x2.setLayout(p6x2Layout);
        p6x2Layout.setHorizontalGroup(
            p6x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p6x2Layout.setVerticalGroup(
            p6x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p6x2);

        p6x3.setBackground(new java.awt.Color(153, 153, 255));
        p6x3.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p6x3Layout = new javax.swing.GroupLayout(p6x3);
        p6x3.setLayout(p6x3Layout);
        p6x3Layout.setHorizontalGroup(
            p6x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p6x3Layout.setVerticalGroup(
            p6x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p6x3);

        p6x4.setBackground(new java.awt.Color(153, 153, 255));
        p6x4.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p6x4Layout = new javax.swing.GroupLayout(p6x4);
        p6x4.setLayout(p6x4Layout);
        p6x4Layout.setHorizontalGroup(
            p6x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p6x4Layout.setVerticalGroup(
            p6x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p6x4);

        p6x5.setBackground(new java.awt.Color(255, 255, 102));
        p6x5.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p6x5Layout = new javax.swing.GroupLayout(p6x5);
        p6x5.setLayout(p6x5Layout);
        p6x5Layout.setHorizontalGroup(
            p6x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p6x5Layout.setVerticalGroup(
            p6x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p6x5);

        p6x6.setBackground(new java.awt.Color(153, 153, 255));
        p6x6.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p6x6Layout = new javax.swing.GroupLayout(p6x6);
        p6x6.setLayout(p6x6Layout);
        p6x6Layout.setHorizontalGroup(
            p6x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p6x6Layout.setVerticalGroup(
            p6x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p6x6);

        p6x7.setBackground(new java.awt.Color(255, 255, 102));
        p6x7.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p6x7Layout = new javax.swing.GroupLayout(p6x7);
        p6x7.setLayout(p6x7Layout);
        p6x7Layout.setHorizontalGroup(
            p6x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p6x7Layout.setVerticalGroup(
            p6x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p6x7);

        p6x8.setBackground(new java.awt.Color(153, 153, 255));
        p6x8.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p6x8Layout = new javax.swing.GroupLayout(p6x8);
        p6x8.setLayout(p6x8Layout);
        p6x8Layout.setHorizontalGroup(
            p6x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p6x8Layout.setVerticalGroup(
            p6x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p6x8);

        p7x1.setBackground(new java.awt.Color(153, 153, 255));
        p7x1.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p7x1Layout = new javax.swing.GroupLayout(p7x1);
        p7x1.setLayout(p7x1Layout);
        p7x1Layout.setHorizontalGroup(
            p7x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p7x1Layout.setVerticalGroup(
            p7x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p7x1);

        p7x2.setBackground(new java.awt.Color(255, 255, 102));
        p7x2.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p7x2Layout = new javax.swing.GroupLayout(p7x2);
        p7x2.setLayout(p7x2Layout);
        p7x2Layout.setHorizontalGroup(
            p7x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p7x2Layout.setVerticalGroup(
            p7x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p7x2);

        p7x3.setBackground(new java.awt.Color(153, 153, 255));
        p7x3.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p7x3Layout = new javax.swing.GroupLayout(p7x3);
        p7x3.setLayout(p7x3Layout);
        p7x3Layout.setHorizontalGroup(
            p7x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p7x3Layout.setVerticalGroup(
            p7x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p7x3);

        p7x4.setBackground(new java.awt.Color(153, 153, 255));
        p7x4.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p7x4Layout = new javax.swing.GroupLayout(p7x4);
        p7x4.setLayout(p7x4Layout);
        p7x4Layout.setHorizontalGroup(
            p7x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p7x4Layout.setVerticalGroup(
            p7x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p7x4);

        p7x5.setBackground(new java.awt.Color(255, 255, 102));
        p7x5.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p7x5Layout = new javax.swing.GroupLayout(p7x5);
        p7x5.setLayout(p7x5Layout);
        p7x5Layout.setHorizontalGroup(
            p7x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p7x5Layout.setVerticalGroup(
            p7x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p7x5);

        p7x6.setBackground(new java.awt.Color(153, 153, 255));
        p7x6.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p7x6Layout = new javax.swing.GroupLayout(p7x6);
        p7x6.setLayout(p7x6Layout);
        p7x6Layout.setHorizontalGroup(
            p7x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p7x6Layout.setVerticalGroup(
            p7x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p7x6);

        p7x7.setBackground(new java.awt.Color(255, 255, 102));
        p7x7.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p7x7Layout = new javax.swing.GroupLayout(p7x7);
        p7x7.setLayout(p7x7Layout);
        p7x7Layout.setHorizontalGroup(
            p7x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p7x7Layout.setVerticalGroup(
            p7x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p7x7);

        p7x8.setBackground(new java.awt.Color(153, 153, 255));
        p7x8.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p7x8Layout = new javax.swing.GroupLayout(p7x8);
        p7x8.setLayout(p7x8Layout);
        p7x8Layout.setHorizontalGroup(
            p7x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p7x8Layout.setVerticalGroup(
            p7x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p7x8);

        p8x1.setBackground(new java.awt.Color(153, 153, 255));
        p8x1.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p8x1Layout = new javax.swing.GroupLayout(p8x1);
        p8x1.setLayout(p8x1Layout);
        p8x1Layout.setHorizontalGroup(
            p8x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p8x1Layout.setVerticalGroup(
            p8x1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p8x1);

        p8x2.setBackground(new java.awt.Color(255, 255, 102));
        p8x2.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p8x2Layout = new javax.swing.GroupLayout(p8x2);
        p8x2.setLayout(p8x2Layout);
        p8x2Layout.setHorizontalGroup(
            p8x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p8x2Layout.setVerticalGroup(
            p8x2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p8x2);

        p8x3.setBackground(new java.awt.Color(255, 255, 102));
        p8x3.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p8x3Layout = new javax.swing.GroupLayout(p8x3);
        p8x3.setLayout(p8x3Layout);
        p8x3Layout.setHorizontalGroup(
            p8x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p8x3Layout.setVerticalGroup(
            p8x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p8x3);

        p8x4.setBackground(new java.awt.Color(255, 255, 102));
        p8x4.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p8x4Layout = new javax.swing.GroupLayout(p8x4);
        p8x4.setLayout(p8x4Layout);
        p8x4Layout.setHorizontalGroup(
            p8x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p8x4Layout.setVerticalGroup(
            p8x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p8x4);

        p8x5.setBackground(new java.awt.Color(255, 255, 102));
        p8x5.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p8x5Layout = new javax.swing.GroupLayout(p8x5);
        p8x5.setLayout(p8x5Layout);
        p8x5Layout.setHorizontalGroup(
            p8x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p8x5Layout.setVerticalGroup(
            p8x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p8x5);

        p8x6.setBackground(new java.awt.Color(153, 153, 255));
        p8x6.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p8x6Layout = new javax.swing.GroupLayout(p8x6);
        p8x6.setLayout(p8x6Layout);
        p8x6Layout.setHorizontalGroup(
            p8x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p8x6Layout.setVerticalGroup(
            p8x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p8x6);

        p8x7.setBackground(new java.awt.Color(255, 255, 102));
        p8x7.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p8x7Layout = new javax.swing.GroupLayout(p8x7);
        p8x7.setLayout(p8x7Layout);
        p8x7Layout.setHorizontalGroup(
            p8x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p8x7Layout.setVerticalGroup(
            p8x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p8x7);

        p8x8.setBackground(new java.awt.Color(255, 255, 102));
        p8x8.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout p8x8Layout = new javax.swing.GroupLayout(p8x8);
        p8x8.setLayout(p8x8Layout);
        p8x8Layout.setHorizontalGroup(
            p8x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p8x8Layout.setVerticalGroup(
            p8x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gameGrid.add(p8x8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gridUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gridUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gridUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gridUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gridUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gameGrid;
    private javax.swing.JPanel p1x1;
    private javax.swing.JPanel p1x2;
    private javax.swing.JPanel p1x3;
    private javax.swing.JPanel p1x4;
    private javax.swing.JPanel p1x5;
    private javax.swing.JPanel p1x6;
    private javax.swing.JPanel p1x7;
    private javax.swing.JPanel p1x8;
    private javax.swing.JPanel p2x1;
    private javax.swing.JPanel p2x2;
    private javax.swing.JPanel p2x3;
    private javax.swing.JPanel p2x4;
    private javax.swing.JPanel p2x5;
    private javax.swing.JPanel p2x6;
    private javax.swing.JPanel p2x7;
    private javax.swing.JPanel p2x8;
    private javax.swing.JPanel p3x1;
    private javax.swing.JPanel p3x2;
    private javax.swing.JPanel p3x3;
    private javax.swing.JPanel p3x4;
    private javax.swing.JPanel p3x5;
    private javax.swing.JPanel p3x6;
    private javax.swing.JPanel p3x7;
    private javax.swing.JPanel p3x8;
    private javax.swing.JPanel p4x1;
    private javax.swing.JPanel p4x2;
    private javax.swing.JPanel p4x3;
    private javax.swing.JPanel p4x4;
    private javax.swing.JPanel p4x5;
    private javax.swing.JPanel p4x6;
    private javax.swing.JPanel p4x7;
    private javax.swing.JPanel p4x8;
    private javax.swing.JPanel p5x1;
    private javax.swing.JPanel p5x2;
    private javax.swing.JPanel p5x3;
    private javax.swing.JPanel p5x4;
    private javax.swing.JPanel p5x5;
    private javax.swing.JPanel p5x6;
    private javax.swing.JPanel p5x7;
    private javax.swing.JPanel p5x8;
    private javax.swing.JPanel p6x1;
    private javax.swing.JPanel p6x2;
    private javax.swing.JPanel p6x3;
    private javax.swing.JPanel p6x4;
    private javax.swing.JPanel p6x5;
    private javax.swing.JPanel p6x6;
    private javax.swing.JPanel p6x7;
    private javax.swing.JPanel p6x8;
    private javax.swing.JPanel p7x1;
    private javax.swing.JPanel p7x2;
    private javax.swing.JPanel p7x3;
    private javax.swing.JPanel p7x4;
    private javax.swing.JPanel p7x5;
    private javax.swing.JPanel p7x6;
    private javax.swing.JPanel p7x7;
    private javax.swing.JPanel p7x8;
    private javax.swing.JPanel p8x1;
    private javax.swing.JPanel p8x2;
    private javax.swing.JPanel p8x3;
    private javax.swing.JPanel p8x4;
    private javax.swing.JPanel p8x5;
    private javax.swing.JPanel p8x6;
    private javax.swing.JPanel p8x7;
    private javax.swing.JPanel p8x8;
    // End of variables declaration//GEN-END:variables
}
